# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://10.0.2.2:3128"
    config.proxy.https    = "http://10.0.2.2:3128"
    config.proxy.no_proxy = "localhost,127.0.0.1,.bosch.com"
  end

  # enabel ssh agent forwarding, to use same ssh key as on host in vagrantbox
  config.ssh.forward_agent = true
  # disable the default share, since I got the Vagrantfile under version control in homestow
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.provision "file", source: "#{ENV["CREDENTIALS_DIR"]}/.git-credentials", destination: ".git-credentials"
  config.vm.provision "file", source: "#{ENV["CREDENTIALS_DIR"]}/id_rsa", destination: ".ssh/id_rsa"
  config.vm.provision "file", source: "#{ENV["CREDENTIALS_DIR"]}/id_rsa.pub", destination: ".ssh/id_rsa.pub"
  config.vm.provision "shell", privileged: true, inline: "pacman -Syy"
  config.vm.provision "shell", privileged: true, inline: "pacman -S --noconfirm git"
  config.vm.provision "shell", privileged: false, inline: "git config --global credential.helper store"
  config.vm.provision "shell", privileged: false, inline: "rm -f -r ansible && git clone https://github.com/benjaminbauer/ansible.git"
  config.vm.provision "shell", privileged: true, inline: "sh ansible/pre-ansible/install_ansible.sh"
  config.vm.provision "shell", privileged: false, inline: "sh ansible/arch/run-ansible-win-10.sh"
end

