# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"

  # enabel ssh agent forwarding, to use same ssh key as on host in vagrantbox
  config.ssh.forward_agent = true
  # disable the default share, since I got the Vagrantfile under version control in homestow
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # explicitly set owner, since default is 'vagrant'
  config.vm.synced_folder "/home/bab1imb/Documents", "/home/vagrant/Documents"

  config.vm.provider "virtualbox" do |vb|
    #start with GUI
    #vb.gui = true
    #vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
  end
end
